# See: https://www.netlifycms.org/docs/add-to-your-site/
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "assets/uploads" # Media files will be stored in the repo under images/uploads

# For fields, see: https://www.netlifycms.org/docs/widgets/
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "collections/_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", default: ""}
      - {label: "Published", name: "published", widget: "boolean", default: true}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      # - {label: "Featured Image", name: "thumbnail", widget: "image"}
      # - {label: "Body", name: "body", widget: "markdown"}
      - label: "Body"
        name: "body"
        widget: "markdown"
        default: |
          {%- include basepaths.html -%}

          {% include toc.html %}

  - name: "pages"
    label: "Pages"
    files:
      - file: "about.md"
        label: "Résumé"
        name: "resume"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string"}
          - {label: "Published", name: "published", widget: "boolean", default: true}
          - {label: "Body", name: "body", widget: "markdown"}
